### ISSUE TITLE
Move dUSD modules to Ardana dApps

### ISSUE THREAD

**Issue by epiro-ps** [ArdanaLabs/Ardana-dApps#42]
We want the price-feeder and any other relevant modules copied to Ardana Apps such that each one gets a dev shell, tests, and a build.

**Comment by Geometer1729** [comment]
adding ` nix run .#offchain:dusd-api:test:local` seems like it should be part of a later pr that starts the offchain/dUSD-api

**Comment by epiro-ps** [comment]
@Geometer1729 Good point. Removed.
