### ISSUE TITLE
Run an optimizer on our PNGs before committing to the repo

### ISSUE THREAD

**Issue by toastal** [ArdanaLabs/Ardana-dApps#49]
`zopflipng` (`nix-shell -p zopfli`) or `optipng` (`nix-shell -p optipng`) can reduce the size of our PNGs by about 33% while losing almost nothing. I verified that there is no 'useful' metadata on the images with `exiftool` that was lost after optimizing as well (though maybe there's some metadata like licensing we'd want to add???). By reducing the size of these artifacts now, we can reduce the size of this repo when checking it out--as well as the size of the images delivered to users.

ZopfliPNG offers slightly better compression (2-5%), but OptiPNG retains the "Gamma" and "SRGB Rendering intent" which may be useful later editing (probably not, but you never know). Either one is acceptable depending on how you feel about aggressive vs. conservative.

required for #22

**Comment by leomayleomay** [comment]
closed PR: https://github.com/ArdanaLabs/Ardana-dApps/pull/50
